/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import java.awt.Color;

/**
 *
 * @author USER
 */
public class LoginGUI extends javax.swing.JFrame {

    //Variables for dragging
    int xMouse;
    int yMouse;
    /**
     * Creates new form LoginGUI
     */
    public LoginGUI() {
        initComponents();
        //Register Panel is not visible at the first opening
        registerPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPane = new javax.swing.JPanel();
        registerPanel = new javax.swing.JPanel();
        usernameRegister = new javax.swing.JTextField();
        registerWide = new javax.swing.JLabel();
        passwordRegisterAgain = new javax.swing.JPasswordField();
        passwordRegister = new javax.swing.JPasswordField();
        panelBackground = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        register = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        drag = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1280, 720));

        contentPane.setPreferredSize(new java.awt.Dimension(1280, 720));
        contentPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registerPanel.setPreferredSize(new java.awt.Dimension(717, 452));
        registerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernameRegister.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        usernameRegister.setForeground(new java.awt.Color(204, 204, 204));
        usernameRegister.setText("Username");
        usernameRegister.setBorder(null);
        usernameRegister.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameRegisterFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameRegisterFocusLost(evt);
            }
        });
        registerPanel.add(usernameRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 530, 50));

        registerWide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/pics/registerButtonWide.png"))); // NOI18N
        registerWide.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerWide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerWideMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registerWideMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registerWideMouseExited(evt);
            }
        });
        registerPanel.add(registerWide, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 660, 70));

        passwordRegisterAgain.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        passwordRegisterAgain.setForeground(new java.awt.Color(204, 204, 204));
        passwordRegisterAgain.setText("Password");
        passwordRegisterAgain.setBorder(null);
        passwordRegisterAgain.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordRegisterAgainFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordRegisterAgainFocusLost(evt);
            }
        });
        passwordRegisterAgain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordRegisterAgainActionPerformed(evt);
            }
        });
        registerPanel.add(passwordRegisterAgain, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 277, 490, 50));

        passwordRegister.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        passwordRegister.setForeground(new java.awt.Color(204, 204, 204));
        passwordRegister.setText("Password");
        passwordRegister.setBorder(null);
        passwordRegister.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordRegisterFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordRegisterFocusLost(evt);
            }
        });
        registerPanel.add(passwordRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 490, 50));

        panelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/pics/registerPanel.png"))); // NOI18N
        registerPanel.add(panelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, 720, -1));

        contentPane.add(registerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 720, -1));

        login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/pics/loginbuttonfinal.png"))); // NOI18N
        login.setText("Buton");
        login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginMouseExited(evt);
            }
        });
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        contentPane.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, 620, 60));

        username.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        username.setForeground(new java.awt.Color(204, 204, 204));
        username.setText("Username");
        username.setBorder(null);
        username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameFocusLost(evt);
            }
        });
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        contentPane.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 540, 50));

        password.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        password.setForeground(new java.awt.Color(204, 204, 204));
        password.setText("Password");
        password.setBorder(null);
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });
        contentPane.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 540, 50));

        register.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/pics/registerButton.png"))); // NOI18N
        register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registerMouseExited(evt);
            }
        });
        contentPane.add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        contentPane.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 0, 40, 40));

        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        contentPane.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 0, 40, 40));

        drag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                dragMouseDragged(evt);
            }
        });
        drag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dragMousePressed(evt);
            }
        });
        contentPane.add(drag, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/pics/loginPage.png"))); // NOI18N
        contentPane.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(contentPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(contentPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusGained
        if (username.getText().equals("Username")) {
            username.setText("");
            username.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_usernameFocusGained

    private void usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusLost
        if (username.getText().isEmpty()) {
            username.setForeground(Color.GRAY);
            username.setText("Username");
        }
    }//GEN-LAST:event_usernameFocusLost

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
        if (password.getText().equals("Password")) {
            password.setText("");
            password.setForeground(Color.BLACK);
        }    
        
    }//GEN-LAST:event_passwordFocusGained

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusLost
        if(password.getText().isEmpty()){
            password.setForeground(Color.GRAY);
            password.setText("Password");
        }
    }//GEN-LAST:event_passwordFocusLost

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginActionPerformed

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void dragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_dragMousePressed

    private void dragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragMouseDragged
        int x = evt.getXOnScreen();
	int y = evt.getYOnScreen();				
	this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_dragMouseDragged

    private void loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseEntered
        login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/pics/loginButtonHoverFinal.png")));
    }//GEN-LAST:event_loginMouseEntered

    private void loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseExited
        login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/pics/loginButtonFinal.png")));
    }//GEN-LAST:event_loginMouseExited

    private void registerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseEntered
        register.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/pics/registerButtonHover.png")));
    }//GEN-LAST:event_registerMouseEntered

    private void registerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseExited
        register.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/pics/registerButton.png")));
    }//GEN-LAST:event_registerMouseExited

    private void registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseClicked
        registerPanel.setVisible(true);
    }//GEN-LAST:event_registerMouseClicked

    private void registerWideMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerWideMouseEntered
        registerWide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/pics/registerButtonWideHover.png")));
    }//GEN-LAST:event_registerWideMouseEntered

    private void registerWideMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerWideMouseExited
        registerWide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/pics/registerButtonWide.png")));
    }//GEN-LAST:event_registerWideMouseExited

    private void usernameRegisterFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameRegisterFocusGained
        if (usernameRegister.getText().equals("Username")) {
            usernameRegister.setText("");
            usernameRegister.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_usernameRegisterFocusGained

    private void usernameRegisterFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameRegisterFocusLost
        if (usernameRegister.getText().isEmpty()) {
            usernameRegister.setForeground(Color.GRAY);
            usernameRegister.setText("Username");
        }
    }//GEN-LAST:event_usernameRegisterFocusLost

    private void passwordRegisterAgainFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordRegisterAgainFocusGained
        if (passwordRegisterAgain.getText().equals("Password")) {
            passwordRegisterAgain.setText("");
            passwordRegisterAgain.setForeground(Color.BLACK);
        }    
    }//GEN-LAST:event_passwordRegisterAgainFocusGained

    private void passwordRegisterAgainFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordRegisterAgainFocusLost
        if(passwordRegisterAgain.getText().isEmpty()){
           passwordRegisterAgain.setForeground(Color.GRAY);
           passwordRegisterAgain.setText("Password");
        }
    }//GEN-LAST:event_passwordRegisterAgainFocusLost

    private void passwordRegisterFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordRegisterFocusGained
        if (passwordRegister.getText().equals("Password")) {
            passwordRegister.setText("");
            passwordRegister.setForeground(Color.BLACK);
        }    
    }//GEN-LAST:event_passwordRegisterFocusGained

    private void passwordRegisterFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordRegisterFocusLost
        if(passwordRegister.getText().isEmpty()){
           passwordRegister.setForeground(Color.GRAY);
           passwordRegister.setText("Password");
        }
    }//GEN-LAST:event_passwordRegisterFocusLost

    private void passwordRegisterAgainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordRegisterAgainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordRegisterAgainActionPerformed

    private void registerWideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerWideMouseClicked
        //--------------- Override here ---------------//
        registerPanel.setVisible(false);
    }//GEN-LAST:event_registerWideMouseClicked

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
        //Temprorary
        MainGUI mainGUI = new MainGUI();
        mainGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_loginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel close;
    private javax.swing.JPanel contentPane;
    private javax.swing.JLabel drag;
    private javax.swing.JButton login;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel panelBackground;
    private javax.swing.JPasswordField password;
    private javax.swing.JPasswordField passwordRegister;
    private javax.swing.JPasswordField passwordRegisterAgain;
    private javax.swing.JLabel register;
    private javax.swing.JPanel registerPanel;
    private javax.swing.JLabel registerWide;
    private javax.swing.JTextField username;
    private javax.swing.JTextField usernameRegister;
    // End of variables declaration//GEN-END:variables
}
